In [5]:
from PIL import Image
im = Image.open("Downloads/Pena.jpeg")

In [6]:
im.show()

In [7]:
import numpy as np

width = 5
height = 4

arr = np.zeros([height, width, 3], dtype=np.uint8)

In [8]:
arr[:,:] = [255, 128, 0]

In [11]:
from PIL import Image

img = Image.fromarray(arr)
img.save('imrgb.png')

In [308]:
import numpy as np
from PIL import Image

array = np.zeros([100, 200, 4], dtype=np.uint8)
array[:,:100] = [255, 128, 0, 255] # оранжевый цвет для левого края
array[:,100:] = [0, 0, 255, 255]   # голубой цвет для правого

# установление прозрачности в зависимости от положения x
#for x in range(200):
 #   for y in range(100):
  #      array[y, x, 3] = x

img = Image.fromarray(array)

img.save('imrgba.png')


In [309]:
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('imrgba.png').convert('RGB'))


In [214]:
for row in img:
    print (*row)

[255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 128   0] [255 1

In [53]:
import numpy as np
from PIL import Image

array = np.zeros([100, 200, 4], dtype=np.uint8)
array[:,:100] = [255, 255, 255, 255] # белый цвет для левого края
array[:,100:] = [0, 0, 0, 255]   # черный цвет для правого

# установление прозрачности в зависимости от положения x
#for x in range(200):
  #  for y in range(100):
     #   array[y, x, 3] = x

img = Image.fromarray(array)

img.save('blwh.png')


In [54]:
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('blwh.png').convert('RGB'))

In [55]:
for row in img:
    print (*row)

[255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 255 255] [255 2

In [217]:
def get_gradient_2d(start, stop, width, height, is_horizontal):
    if is_horizontal:
        return np.tile(np.linspace(start, stop, width), (height, 1))
    else:
        return np.tile(np.linspace(start, stop, height), (width, 1)).T

In [218]:
def get_gradient_3d(width, height, start_list, stop_list, is_horizontal_list):
    result = np.zeros((height, width, len(start_list)), dtype=float)

    for i, (start, stop, is_horizontal) in enumerate(zip(start_list, stop_list, is_horizontal_list)):
        result[:, :, i] = get_gradient_2d(start, stop, width, height, is_horizontal)

    return result


In [219]:
from PIL import Image

array = get_gradient_3d(5, 1, (0, 0, 0), (255, 255, 255), (True, True, True))
Image.fromarray(np.uint8(array)).save('gray_gradient_h.jpg', quality=95)

In [288]:
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('gray_gradient_h.jpg').convert('RGB'))

In [289]:
for row in img:
    print (*row)

[0 0 0] [63 63 63] [127 127 127] [192 192 192] [255 255 255]


In [290]:
img[0, 1][0]-img[0, 0][0]

63

In [291]:
r=img.shape[1]
checker=[9,-1,0]
for j in range(1, r):
    for i in 0,1,2:
        if(( ((img[0, j][i]-img[0, j-1][i])>=0) and (checker[i]>=0)) 
        or ((img[0, j][i]-img[0, j-1][i])<=0) and (checker[i]<=0)):
            print('ok')
        else:
            print('bad')

ok
bad
ok
ok
bad
ok
ok
bad
ok
ok
bad
ok


In [343]:
#проход по одному цвету (1), работает
Fup={}
Fdown={}
Fup[0]=1
Fdown[0]=1
for i in range(1,img.shape[1]):
    if (img[0,i][1]<img[0,i-1][1]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=1
    if (img[0,i][1]>img[0,i-1][1]):
        Fup[i]=Fup[i-1]+1
        Fdown[i]=1
    if (img[0,i][1]==img[0,i-1][1]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=Fup[i-1]+1
    F[i]=max(Fup[i], Fdown[i])
for i in range(0,img.shape[1]):
    print (Fup[i], Fdown[i])
    


1 1
2 2
3 1
4 2
5 1
6 2
7 1
8 2
9 1
10 2
1 3
2 4
3 1
4 2
1 3
2 4


In [351]:
#проход по одному цвету (0), работает, считает Fdown, Fup, F
Fup={}
Fdown={}
Fup[0]=1
Fdown[0]=1
for i in range(1,img.shape[1]):
    if (img[0,i][0]<img[0,i-1][0]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=1
    if (img[0,i][0]>img[0,i-1][0]):
        Fup[i]=Fup[i-1]+1
        Fdown[i]=1
    if (img[0,i][0]==img[0,i-1][0]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=Fup[i-1]+1
    F[i]=max(Fup[i], Fdown[i])
for i in range(0,img.shape[1]):
    print (F[i])

1
2
3
4
3
4
5
6
3
4
3
4
3
4
3
4


In [347]:
#проход по одному цвету (2), работает
Fup={}
Fdown={}
Fup[0]=1
Fdown[0]=1
for i in range(1,img.shape[1]):
    if (img[0,i][2]<img[0,i-1][2]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=1
    if (img[0,i][2]>img[0,i-1][2]):
        Fup[i]=Fup[i-1]+1
        Fdown[i]=1
    if (img[0,i][2]==img[0,i-1][2]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=Fup[i-1]+1
    F[i]=max(Fup[i], Fdown[i])
for i in range(0,img.shape[1]):
    print (Fup[i], Fdown[i])

1 1
2 2
3 1
4 2
5 1
6 2
1 3
2 4
1 5
2 6
3 1
4 2
1 3
2 4
1 5
2 6


In [384]:
#проход по трем цветам склееный вручную (эмодзи клоуна)
#проход по одному цвету (0), работает, считает Fdown, Fup, F
Fup={}
Fdown={}
Fup[0]=1
Fdown[0]=1
for i in range(1,img.shape[1]):
    if (img[0,i][0]<img[0,i-1][0]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=1
    if (img[0,i][0]>img[0,i-1][0]):
        Fup[i]=Fup[i-1]+1
        Fdown[i]=1
    if (img[0,i][0]==img[0,i-1][0]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=Fup[i-1]+1
    F[i]=max(Fup[i], Fdown[i])
#for i in range(0,img.shape[1]):
 #   print (Fup[i], Fdown[i])
#for i in range(0,img.shape[1]):
   # print (F[i])
#проход по одному цвету (1), работает
Fup[0]=1
Fdown[0]=1
for i in range(1,img.shape[1]):
    if (img[0,i][1]<img[0,i-1][1]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=1
    if (img[0,i][1]>img[0,i-1][1]):
        Fup[i]=Fup[i-1]+1
        Fdown[i]=1
    if (img[0,i][1]==img[0,i-1][1]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=Fup[i-1]+1
    F[i]=min(max(Fup[i], Fdown[i]), F[i])
#for i in range(0,img.shape[1]):
 #   print (Fup[i], Fdown[i])

#проход по одному цвету (2), работает
Fup[0]=1
Fdown[0]=1
for i in range(1,img.shape[1]):
    if (img[0,i][2]<img[0,i-1][2]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=1
    if (img[0,i][2]>img[0,i-1][2]):
        Fup[i]=Fup[i-1]+1
        Fdown[i]=1
    if (img[0,i][2]==img[0,i-1][2]):
        Fdown[i]=Fdown[i-1]+1
        Fup[i]=Fup[i-1]+1
    F[i]=min(max(Fup[i], Fdown[i]), F[i])
#for i in range(0,img.shape[1]):
 #   print (Fup[i], Fdown[i])
for i in range(0,img.shape[1]):
    print (F[i])

1
2
3
3
4
3
4
3
4
3
4
3
4
3
4
5


In [407]:
#пытаюсь сделать рабочую штуку для двух строк пожелай мне удачи
#проход по трем цветам склееный вручную (эмодзи клоуна)
#проход по одному цвету (0), работает, считает Fdown, Fup, F
Result = [ [0]*img.shape[1] for i in range(img.shape[0]) ]
for k in range(0, img.shape[0]):
    Fup={}
    Fdown={}
    Fup[0]=1
    Fdown[0]=1
    for i in range(1,img.shape[1]):
        if (img[k,i][0]<img[k,i-1][0]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=1
        if (img[k,i][0]>img[k,i-1][0]):
            Fup[i]=Fup[i-1]+1
            Fdown[i]=1
        if (img[k,i][0]==img[k,i-1][0]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=Fup[i-1]+1
        F[i]=max(Fup[i], Fdown[i])
    #for i in range(0,img.shape[1]):
     #   print (Fup[i], Fdown[i])
    #for i in range(0,img.shape[1]):
       # print (F[i])
    #проход по одному цвету (1), работает
    Fup[0]=1
    Fdown[0]=1
    for i in range(1,img.shape[1]):
        if (img[k,i][1]<img[k,i-1][1]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=1
        if (img[k,i][1]>img[k,i-1][1]):
            Fup[i]=Fup[i-1]+1
            Fdown[i]=1
        if (img[k,i][1]==img[k,i-1][1]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=Fup[i-1]+1
        F[i]=min(max(Fup[i], Fdown[i]), F[i])
    #for i in range(0,img.shape[1]):
     #   print (Fup[i], Fdown[i])

    #проход по одному цвету (2), работает
    Fup[0]=1
    Fdown[0]=1
    for i in range(1,img.shape[1]):
        if (img[k,i][2]<img[k,i-1][2]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=1
        if (img[k,i][2]>img[k,i-1][2]):
            Fup[i]=Fup[i-1]+1
            Fdown[i]=1
        if (img[k,i][2]==img[k,i-1][2]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=Fup[i-1]+1
        F[i]=min(max(Fup[i], Fdown[i]), F[i])
    #for i in range(0,img.shape[1]):
     #   print (Fup[i], Fdown[i])
    for i in range(0,img.shape[1]):
        Result[k][i]=F[i]
for i in range(img.shape[0]):
    for k in range (img.shape[1]):
        print(Result[i][k], end = ' ')
    print()  

1 2 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 2 3 3 2 3 4 4 2 2 2 
1 2 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 2 2 2 2 2 2 3 4 4 2 2 2 
1 2 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 5 6 5 2 3 3 2 2 2 
1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 4 4 2 2 2 2 2 
1 2 2 3 4 5 6 6 2 3 3 4 5 6 5 6 3 2 2 3 4 3 2 3 4 4 2 2 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 2 2 2 
1 2 3 4 5 6 7 8 2 3 3 2 3 4 5 6 7 8 9 10 11 12 13 14 15 15 2 2 2 
1 2 3 4 5 6 7 3 4 5 6 5 6 3 4 5 6 5 6 3 4 3 2 3 4 4 2 2 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 2 2 2 3 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 2 2 3 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 2 3 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 2 2 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1

In [ ]:
#пытаюсь сократить рабочую штуку
#проход по трем цветам склееный вручную (эмодзи клоуна)
#проход по одному цвету (0), работает, считает Fdown, Fup, F
Result1 = [ [0]*img.shape[1] for i in range(img.shape[0]) ]
Fup={}
Fdown={}
for k in range(0, img.shape[0]):
    for j in range(0,3):
        Fup[0]=1
        Fdown[0]=1
        for i in range(1,img.shape[1]):
            if (img[k,i][j]<img[k,i-1][j]):
                Fdown[i]=Fdown[i-1]+1
                Fup[i]=1
            if (img[k,i][j]>img[k,i-1][j]):
                Fup[i]=Fup[i-1]+1
                Fdown[i]=1
            if (img[k,i][j]==img[k,i-1][j]):
                Fdown[i]=Fdown[i-1]+1
                Fup[i]=Fup[i-1]+1
            if (j>0):
                F[i]=min(max(Fup[i], Fdown[i]), F[i])
            if (j==0):
                F[i]=max(Fup[i], Fdown[i])
    for i in range(0,img.shape[1]):
        Result1[k][i]=F[i]
for i in range(img.shape[0]):
    for k in range (img.shape[1]):
        print(Result1[i][k], end = ' ')
    print()  

In [441]:
#пытаюсь сделать то же самое для столбцов
#проход по трем цветам склееный вручную (эмодзи клоуна)
#проход по одному цвету (0), работает, считает Fdown, Fup, F
Result2 = [ [0]*img.shape[1] for i in range(img.shape[0]) ]
Fup={}
Fdown={}
for k in range(0, img.shape[1]):
    for j in range(0,3):
        Fup[0]=1
        Fdown[0]=1
        F[0]=1
        for i in range(1,img.shape[0]):
            if (img[i,k][j]<img[i-1,k][j]):
                Fdown[i]=Fdown[i-1]+1
                Fup[i]=1
            if (img[i,k][j]>img[i-1,k][j]):
                Fup[i]=Fup[i-1]+1
                Fdown[i]=1
            if (img[i,k][j]==img[i-1,k][j]):
                Fdown[i]=Fdown[i-1]+1
                Fup[i]=Fup[i-1]+1
            if (j>0):
                F[i]=min(max(Fup[i], Fdown[i]), F[i])
            if (j==0):
                F[i]=max(Fup[i], Fdown[i])
    for i in range(0,img.shape[0]):
        Result2[i][k]=F[i]
for i in range(img.shape[0]):
    for k in range (img.shape[1]):
        print(Result2[i][k], end = ' ')
    print()  

1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 2 2 2 3 3 3 3 3 3 3 
2 4 2 2 2 2 4 4 4 4 3 3 4 4 4 4 2 4 2 2 3 3 2 4 4 4 4 4 4 
3 5 3 2 3 2 5 5 5 2 2 4 2 5 5 2 2 5 2 2 4 3 3 2 2 5 5 5 5 
3 3 3 2 3 2 3 3 3 2 2 3 2 3 3 2 2 6 2 2 4 2 3 2 2 6 6 6 6 
2 2 2 2 2 2 2 4 2 2 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 6 7 7 7 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 8 8 8 
2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4 9 9 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 5 10 10 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 4 4 6 11 11 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 5 5 7 12 12 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 5 8 13 13 
3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 6 9 14 14 
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 7 15 15 


In [520]:
#хочу совместить Result1 и Result2
#поиск первого прямоугольничка:))))
i=0
k=0
k0=0
while ((Result1[k0][i]<Result1[k0][i+1]) and (i<img.shape[1])):
    i=i+1
print (i)
i0=0
while ((Result2[k][k0]<Result2[k+1][k0]) and (k<img.shape[0])):
    k=k+1
print (k)
kk=k0
for ii in (i0+1, i):
    while ((kk<k) and Result2[kk][ii]<Result2[kk+1][ii]):
        kk=kk+1
    k=min(k,kk)
print (k)
ii=i0
for kk in (k0+1, k):
    while ((ii<i) and Result1[kk][ii]<Result1[kk][ii+1]):
        ii=ii+1
    i=min(i,ii)
print (i)
        

3
2
2
3


In [ ]:
#продолжаю совмещать Result1 и Result2, поиск других прямоугольничков
i0=0
k0=0
x0=0
y0=0
while ((i0<img.shape[1])): #and (k0<img.shape[0])):
    #print("yes")
    i=i0
    k=k0
    if ((i+2<img.shape[1]) and (k+2<img.shape[0])):
        while ((Result1[k0][i]<Result1[k0][i+1]) and (i<img.shape[1])):
            i=i+1
            #print (i)
        while ((Result2[k][i0]<Result2[k+1][i0]) and (k<img.shape[0])):
            k=k+1
        #print (k)
        kk=k0+1
        if (i0<i):
            for ii in (i0, i):
                while ((kk<k) and Result2[kk][ii]<Result2[kk+1][ii]):
                    kk=kk+1
                k=min(k,kk)
            x0=k
            ii=i0+1
            if (k0<k):
                for kk in (k0, k):
                    while ((ii<i) and Result1[kk][ii]<Result1[kk][ii+1]):
                        ii=ii+1
                    i=min(i,ii)
                y0=i
            print(k0, i0, x0, y0)
        i0=i+1
        #k0=k+1
        k0=0
        #print (i0, k0)

0 0 2 3
0 4 2 5
0 6 4 7
0 8 4 9
0 10 2 11
0 12 3 13
0 14 4 15
0 16 1 17
0 19 1 20
0 22 2 24


In [525]:
#цикл не заработал, пробую втупую
i0=0
k0=0
while ((Result1[i0][i]<Result1[i0][i+1]) and (i<img.shape[1])):
    i=i+1
#print (i)
while ((Result2[k][k0]<Result2[k+1][k0]) and (k<img.shape[0])):
    k=k+1
#print (k)
kk=k0+1
for ii in (i0+1, i):
    while ((kk<k) and Result2[kk][ii]<Result2[kk+1][ii]):
        kk=kk+1
    k=max(k,kk)
print (k)
ii=i0+1
for kk in (k0+1, k):
    while ((ii<i) and Result1[kk][ii]<Result2[kk][ii+1]):
        ii=ii+1
    i=max(i,ii)
print (i)
i0=i+1
k0=k+1
while ((Result1[i0][i]<Result1[i0][i+1]) and (i<img.shape[1])):
    i=i+1
#print (i)
while ((Result2[k][k0]<Result2[k+1][k0]) and (k<img.shape[0])):
    k=k+1
#print (k)
kk=k0+1
for ii in (i0+1, i):
    while ((kk<k) and Result2[kk][ii]<Result2[kk+1][ii]):
        kk=kk+1
    k=max(k,kk)
print (k)
ii=i0+1
for kk in (k0+1, k):
    while ((ii<i) and Result1[kk][ii]<Result2[kk][ii+1]):
        ii=ii+1
    i=max(i,ii)
print (i)        

2
3
4
6


In [426]:
#НЕ РАБОТАЕТ проходимся по всем трем цветам и теперь в Fup[i], Fdown[i] хранятся длины наибольших подстрок битов, 
#заканчивающихся на i символе, таких, что подстроку можно считать градиентной заливкой
Fup={}
Fdown={}
Fup[0]=1
Fdown[0]=1
F={}
F[0]=1
for i in range(1,img.shape[1]):
        if (img[0,i][0]<img[0,i-1][0]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=1
        if (img[0,i][0]>img[0,i-1][0]):
            Fup[i]=Fup[i-1]+1
            Fdown[i]=1
        if (img[0,i][0]==img[0,i-1][0]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=Fup[i-1]+1
#for i in range(0,img.shape[1]):
  #  print (Fup[i], Fdown[i])
for i in range(1,img.shape[1]):
    for k in range (1,3):
        if (img[0,i][k]<img[0,i-1][k]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=1
        if (img[0,i][k]>img[0,i-1][k]):
            Fup[i]=Fup[i-1]+1
            Fdown[i]=1
        if (img[0,i][k]==img[0,i-1][k]):
            Fdown[i]=Fdown[i-1]+1
            Fup[i]=Fup[i-1]+1
        F[i]=max(Fdown[i], Fup[i])
for i in range(0,img.shape[1]):
    print (F[i])
    

1
2
3
4
5
6
3
4
5
6
3
4
3
4
5
6
3
4
3
2
3
3
2
3
4
4
2
3
2


In [334]:
#работаем с pixil2.png -- картинка, состоящая из двух пикселей черного и двух пикселей синего цвета

from PIL import Image
im = Image.open("Downloads/pixil2.png")
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('Downloads/pixil2.png').convert('RGB'))
for row in img:
    print (*row)

[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243]


In [385]:
#работаем с pixil22.png -- картинка, состоящая из двух строк пикселей
from PIL import Image
im = Image.open("Downloads/pixil22.png")
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('Downloads/pixil22.png').convert('RGB'))
for row in img:
    print (*row)

[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243] [  3 169 244] [  3 169 244] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [ 76 175  80] [ 76 175  80] [255 235  59] [255 235  59] [244  67  54] [244  67  54]
[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243] [  3 169 244] [  3 169 244] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [  0 150 136] [  0 150 136] [255 235  59] [255 235  59] [244  67  54] [244  67  54]


In [380]:
#работаем с pixil3.png -- картинка, состоящая из одной строки пикселей

from PIL import Image
im = Image.open("Downloads/pixil3.png")
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('Downloads/pixil3.png').convert('RGB'))
for row in img:
    print (*row)

[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243] [  3 169 244] [  3 169 244] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [ 76 175  80] [ 76 175  80] [255 235  59] [255 235  59] [244  67  54] [244  67  54]


In [397]:
#работаем с pixil316.png -- картинка, состоящая из трех строк пикселей

from PIL import Image
im = Image.open("Downloads/pixil316.png")
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('Downloads/pixil316.png').convert('RGB'))
for row in img:
    print (*row)


[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243] [  3 169 244] [  3 169 244] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [ 76 175  80] [ 76 175  80] [255 235  59] [255 235  59] [244  67  54] [244  67  54]
[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243] [  3 169 244] [  3 169 244] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [  0 150 136] [  0 150 136] [255 235  59] [255 235  59] [244  67  54] [244  67  54]
[244  67  54] [244  67  54] [  3 169 244] [  3 169 244] [ 33 150 243] [ 33 150 243] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [  0 150 136] [  0 150 136] [255 235  59] [255 235  59] [244  67  54] [244  67  54]


In [401]:
#работаем с pixil416.png -- картинка, состоящая из четырех строк пикселей

from PIL import Image
im = Image.open("Downloads/pixil416.png")
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('Downloads/pixil416.png').convert('RGB'))
for row in img:
    print (*row)

[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243] [  3 169 244] [  3 169 244] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [ 76 175  80] [ 76 175  80] [255 235  59] [255 235  59] [244  67  54] [244  67  54]
[0 0 0] [0 0 0] [ 33 150 243] [ 33 150 243] [  3 169 244] [  3 169 244] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [  0 150 136] [  0 150 136] [255 235  59] [255 235  59] [244  67  54] [244  67  54]
[244  67  54] [244  67  54] [  3 169 244] [  3 169 244] [ 33 150 243] [ 33 150 243] [  0 188 212] [  0 188 212] [205 220  57] [205 220  57] [  0 150 136] [  0 150 136] [255 235  59] [255 235  59] [244  67  54] [244  67  54]
[0 0 0] [255 255 255] [0 0 0] [255 255 255] [0 0 0] [255 255 255] [0 0 0] [255 255 255] [0 0 0] [255 255 255] [0 0 0] [255 255 255] [0 0 0] [255 255 255] [0 0 0] [255 255 255]


In [ ]:
#работаем с pixilbig.png -- картинка, состоящая из четырех строк пикселей

from PIL import Image
im = Image.open("Downloads/pixilbig.png")
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('Downloads/pixilbig.png').convert('RGB'))
for row in img:
    print (*row)

In [436]:
#работаем с pixilbig_rotated.png -- картинка, состоящая из четырех строк пикселей

from PIL import Image
im = Image.open("Downloads/pixilbig_rotated.png")
import numpy as np
from PIL import Image    #  pip install Pillow

img = np.asarray(Image.open('Downloads/pixilbig_rotated.png').convert('RGB'))
for row in img:
    print (*row)

[ 80  44 105] [103  58 183] [131  48 186] [157   0 255] [191 121 232] [226 188 247] [245 210 238] [205 220  57] [  0 150 136] [156  39 176] [0 0 0] [0 0 0] [244  67  54] [0 0 0] [0 0 0]
[ 80  44 105] [103  58 183] [131  48 186] [157   0 255] [191 121 232] [226 188 247] [245 210 238] [205 220  57] [  0 150 136] [156  39 176] [255 255 255] [255 255 255] [244  67  54] [0 0 0] [0 0 0]
[ 80  44 105] [103  58 183] [131  48 186] [157   0 255] [191 121 232] [226 188 247] [245 210 238] [205 220  57] [  0 150 136] [156  39 176] [0 0 0] [0 0 0] [  3 169 244] [ 33 150 243] [ 33 150 243]
[ 80  44 105] [103  58 183] [131  48 186] [157   0 255] [191 121 232] [226 188 247] [245 210 238] [205 220  57] [  0 150 136] [156  39 176] [0 0 0] [255 255 255] [  3 169 244] [ 33 150 243] [ 33 150 243]
[ 80  44 105] [103  58 183] [131  48 186] [157   0 255] [191 121 232] [226 188 247] [245 210 238] [205 220  57] [  0 150 136] [156  39 176] [0 0 0] [0 0 0] [ 33 150 243] [  3 169 244] [  3 169 244]
[ 80  44 105] [1